import * as React from "react";
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  Badge,
  StatusDot,
} from "@submitpulse/ui";
import type { ClientWorkspace } from "@/lib/scanner-data";

interface WhiteLabelReportPreviewProps {
  clients: ClientWorkspace[];
  agencyName: string;
  accentColor?: string | undefined;
  logoUrl?: string | undefined;
}

export function WhiteLabelReportPreview({
  clients,
  agencyName,
  accentColor = "#4f46e5",
  logoUrl,
}: WhiteLabelReportPreviewProps) {
  const month = new Date().toLocaleString("en-US", { month: "long", year: "numeric" });

  return (
    <Card className="rounded-card shadow-card overflow-hidden">
      <CardHeader>
        <CardTitle>White-label report preview</CardTitle>
        <CardDescription>
          How your clients see their monthly form health report. Branding uses
          your agency logo and accent colour.
        </CardDescription>
      </CardHeader>

      <CardContent>
        {/* Simulated report frame */}
        <div
          className="rounded-md border border-border overflow-hidden"
          role="img"
          aria-label="Report preview for clients"
        >
          {/* Report header */}
          <div
            className="px-6 py-4 flex items-center gap-4 bg-surface border-b-4"
            style={{ borderBottomColor: accentColor }}
          >
            {logoUrl !== undefined && logoUrl !== "" ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img src={logoUrl} alt={`${agencyName} logo`} className="h-8 object-contain" />
            ) : (
              <span
                className="text-lg font-bold"
                style={{ color: accentColor }}
              >
                {agencyName}
              </span>
            )}
            <div className="flex-1" />
            <div className="text-right">
              <p className="text-sm font-semibold text-text-primary">Form Health Report</p>
              <p className="text-xs text-text-muted">{month}</p>
            </div>
          </div>

          {/* Client rows */}
          <div className="divide-y divide-border">
            {clients.slice(0, 4).map((client) => (
              <div
                key={client.id}
                className="px-6 py-3 flex items-center gap-4"
              >
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-text-primary">{client.name}</p>
                  <p className="text-xs text-text-muted">
                    {client.formCount} form{client.formCount !== 1 ? "s" : ""} ·{" "}
                    {client.submissionsThisMonth.toLocaleString("en-US")} submissions
                  </p>
                </div>
                <StatusDot status={client.overallHealth} showLabel />
                {client.healthySummary.failing > 0 && (
                  <Badge variant="danger" size="sm">
                    {client.healthySummary.failing} failing
                  </Badge>
                )}
              </div>
            ))}
          </div>

          {/* Report footer */}
          <div className="px-6 py-3 bg-background border-t border-border text-xs text-text-muted flex items-center justify-between">
            <span>Generated by {agencyName}</span>
            <span style={{ color: accentColor }}>Powered by SubmitPulse</span>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
