/**
 * Billing notice email.
 * Sent for usage threshold warnings, payment failures, subscription changes.
 */

import { brand } from "@submitpulse/config";
import { escapeHtml, escapePlainText } from "./escape.js";
import { htmlLayout, plainTextLayout } from "./layout.js";

export type BillingNoticeKind =
  | "usage_warning"
  | "usage_limit_reached"
  | "payment_failed"
  | "subscription_cancelled"
  | "subscription_renewed"
  | "trial_ending";

export interface BillingNoticeTemplateInput {
  kind: BillingNoticeKind;
  workspaceName: string;
  /** Human-readable headline, generated by the caller. */
  headline: string;
  /** Human-readable body paragraphs. Each string becomes a <p> / paragraph. */
  bodyParagraphs: readonly string[];
  /** Optional URL to a relevant action (billing portal, upgrade page). */
  actionUrl?: string;
  actionLabel?: string;
}

export interface RenderedEmail {
  subject: string;
  html: string;
  text: string;
}

const KIND_SUBJECTS: Record<BillingNoticeKind, string> = {
  usage_warning: "Action needed: approaching submission limit",
  usage_limit_reached: "Submission limit reached",
  payment_failed: "Action needed: payment failed",
  subscription_cancelled: "Subscription cancelled",
  subscription_renewed: "Subscription renewed",
  trial_ending: "Your trial is ending soon",
};

export function renderBillingNotice(input: BillingNoticeTemplateInput): RenderedEmail {
  const subject = KIND_SUBJECTS[input.kind];

  const safeWorkspace = escapeHtml(input.workspaceName);
  const safeHeadline = escapeHtml(input.headline);
  const paragraphs = input.bodyParagraphs
    .map((p) => `<p>${escapeHtml(p)}</p>`)
    .join("\n");
  const textParagraphs = input.bodyParagraphs
    .map((p) => escapePlainText(p))
    .join("\n\n");

  const actionBlock =
    input.actionUrl && input.actionLabel
      ? `<p><a class="btn" href="${escapeHtml(input.actionUrl)}">${escapeHtml(input.actionLabel)}</a></p>`
      : "";

  const html = htmlLayout({
    title: subject,
    bodyContent: `
      <h1>${safeHeadline}</h1>
      <p style="color:#64748b;font-size:13px;">Workspace: <strong>${safeWorkspace}</strong></p>
      ${paragraphs}
      ${actionBlock}
      <p style="font-size:13px;color:#64748b;">Manage billing at <a href="${brand.domains.app}/settings/billing">${brand.domains.app}/settings/billing</a>.</p>
    `,
  });

  const text = plainTextLayout({
    title: subject,
    bodyContent: `${escapePlainText(input.headline)}
Workspace: ${escapePlainText(input.workspaceName)}

${textParagraphs}${input.actionUrl ? `\n\n${escapePlainText(input.actionLabel ?? "Manage billing")}: ${escapePlainText(input.actionUrl)}` : ""}

Manage billing: ${brand.domains.app}/settings/billing`,
  });

  return { subject, html, text };
}
